import type { Metadata } from "next";
import "antd/dist/reset.css";
// C:\Users\HP\Desktop\project\buuk\node_modules\antd\dist\reset.css
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import AppHeader from "../components/header";
import { ConfigProvider } from "antd";
import { Breadcrumb, Layout, } from "antd";
import Footer from "@/components/footer";
const { Header } = Layout;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: "white",
                colorBgContainer: "#0e21ed",
              },
            }}
          >
            
              <AppHeader />
        
            {children}
            <Footer/>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
